# Generated by Django 5.2.7 on 2025-10-24 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(help_text="Amount in IDR")),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("bca_va", "BCA Virtual Account"),
                            ("mandiri_va", "Mandiri Virtual Account"),
                            ("bni_va", "BNI Virtual Account"),
                            ("bri_va", "BRI Virtual Account"),
                            ("permata_va", "Permata Virtual Account"),
                            ("cimb_va", "CIMB Virtual Account"),
                            ("other_va", "Other Virtual Account"),
                            ("indomaret", "Indomaret"),
                            ("alfamart", "Alfamart"),
                            ("gopay", "GO-PAY"),
                            ("akulaku", "Akulaku"),
                            ("shopeepay", "ShopeePay"),
                            ("kredivo", "Kredivo"),
                            ("qris", "Other QRIS"),
                            ("dana", "Dana"),
                            ("danamon_va", "Danamon Virtual Account"),
                            ("bsi_va", "BSI Virtual Account"),
                            ("seabank_va", "SeaBank Virtual Account"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("order_id", models.CharField(max_length=255, unique=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transaction_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("settlement", "Settlement"),
                            ("capture", "Capture"),
                            ("deny", "Deny"),
                            ("cancel", "Cancel"),
                            ("expire", "Expire"),
                            ("failure", "Failure"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("midtrans_response", models.JSONField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="booking.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order_id"], name="payment_pay_order_i_211f02_idx"
                    ),
                    models.Index(
                        fields=["transaction_id"], name="payment_pay_transac_f578fa_idx"
                    ),
                    models.Index(
                        fields=["booking"], name="payment_pay_booking_dc1489_idx"
                    ),
                    models.Index(
                        fields=["user"], name="payment_pay_user_id_e01707_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payment_pay_status_124d3d_idx"
                    ),
                ],
            },
        ),
    ]
