# Generated by Django 5.2.7 on 2025-10-24 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Admin User",
                "verbose_name_plural": "Admin Users",
            },
        ),
        migrations.CreateModel(
            name="AdminSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Setting key", max_length=255, unique=True
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Setting value (JSON, string, or number)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this setting"
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Module this setting belongs to (e.g., 'booking', 'payment', 'courses')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admin_panel.adminuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Setting",
                "verbose_name_plural": "Admin Settings",
                "ordering": ["module", "key"],
            },
        ),
        migrations.CreateModel(
            name="AdminActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view", "View"),
                            ("export", "Export"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Module where action was performed", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the action"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_activities",
                        to="admin_panel.adminuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Activity Log",
                "verbose_name_plural": "Admin Activity Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["admin_user", "-timestamp"],
                        name="admin_panel_admin_u_61244f_idx",
                    ),
                    models.Index(
                        fields=["module", "-timestamp"],
                        name="admin_panel_module_534f8c_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="admin_panel_action_49fe2e_idx",
                    ),
                ],
            },
        ),
    ]
