# Generated by Django 5.2.7 on 2025-10-24 13:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-last_message_at']},
        ),
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together={('user', 'coach')},
        ),
    ]