# Generated by Django 5.2.7 on 2025-10-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_alter_chatsession_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_message_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
