# Generated by Django 5.2.7 on 2025-10-23 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('courses_and_coach', '0001_initial'),
        ('schedule', '0001_initial'),
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='End date and time of the booking', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Start date and time of the booking', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_bookings', to='user_profile.coachprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_bookings', to='courses_and_coach.course'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleslot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['coach', 'start_datetime'], name='booking_boo_coach_i_a848cb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['coach', 'end_datetime'], name='booking_boo_coach_i_988833_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_boo_status_e01616_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='booking_boo_user_id_d9826d_idx'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
