# Generated by Django 5.2.7 on 2025-10-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_unique_together_booking_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
