# Generated by Django 5.2.7 on 2025-10-22 07:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('thumbnailUrl', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('messages', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='main_review_class_r_5595d3_idx',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='class_ref',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coach',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course'], name='main_review_course__534f54_idx'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.category'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='main.booking'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='main.coach'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user'], name='main_chatse_user_id_f65a77_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['coach'], name='main_chatse_coach_i_f1e1ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', True)), fields=('user', 'coach'), name='unique_general_chat_session'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(fields=('user', 'coach', 'booking'), name='unique_booking_chat_session'),
        ),
    ]
