# Generated by Django 5.2.7 on 2025-10-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):


    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(default='Online', help_text='Location where the course takes place (default: Online)', max_length=255)),
                ('price', models.PositiveIntegerField(help_text='Price in the smallest currency unit (e.g., cents, rupiah)')),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('rating', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses_and_coach.category')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user_profile.coachprofile')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(default='Online', help_text='Location where the course takes place (default: Online)', max_length=255)),
                ('price', models.PositiveIntegerField(help_text='Price in the smallest currency unit (e.g., cents, rupiah)')),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('rating', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses_and_coach.category')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user_profile.coachprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coach'], name='courses_and_coach_i_bf78fe_idx'), models.Index(fields=['category'], name='courses_and_categor_04523b_idx'), models.Index(fields=['-created_at'], name='courses_and_created_e6f05c_idx')],
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coach'], name='courses_and_coach_i_bf78fe_idx'), models.Index(fields=['category'], name='courses_and_categor_04523b_idx'), models.Index(fields=['-created_at'], name='courses_and_created_e6f05c_idx')],
            },
        ),
    ]
