# Generated by Django 5.2.7 on 2025-10-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_coachprofile_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='total_minutes_coached',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
