# Generated by Django 5.2.7 on 2025-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_coachprofile_total_minutes_coached'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='balance',
            field=models.PositiveIntegerField(default=0, help_text='Price in the smallest currency unit (e.g., cents, rupiah)'),
        ),
    ]
