"""
Django settings for mami_coach project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE = 'None'

try:
    import dj_database_url  # type: ignore
except Exception:  # pragma: no cover - optional dependency during dev
    dj_database_url = None
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n-asrwt9=fz@@+*_ru@8g*v_5hws!zu52!8*a%j#^xeky+pwj4"

PRODUCTION = os.getenv("PRODUCTION", "False").lower() == "true"
SCHEMA = os.getenv("SCHEMA", "public")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not PRODUCTION


def _split_env_list(name: str) -> list[str]:
    raw = os.getenv(name, "").strip()
    if not raw:
        return []
    return [item.strip() for item in raw.split(",") if item.strip()]


_default_allowed_hosts = [
    "localhost",
    "127.0.0.1",
    "10.0.2.2",
    "kevin-cornellius-mamicoach.pbp.cs.ui.ac.id",
]

# Deployment (Coolify/Traefik/etc): set ALLOWED_HOSTS="your.domain.com,other.domain.com"
ALLOWED_HOSTS = _split_env_list("ALLOWED_HOSTS") or _default_allowed_hosts

# Common reverse-proxy headers (Coolify typically terminates TLS at the proxy)
USE_X_FORWARDED_HOST = os.getenv("USE_X_FORWARDED_HOST", "true").lower() == "true"
if os.getenv("USE_SECURE_PROXY_SSL_HEADER", "true").lower() == "true":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# CSRF Trusted Origins
# Deployment: set CSRF_TRUSTED_ORIGINS="https://your.domain.com,https://other.domain.com"
CSRF_TRUSTED_ORIGINS = _split_env_list("CSRF_TRUSTED_ORIGINS") or [
    "https://kevin-cornellius-mamicoach.pbp.cs.ui.ac.id",
]

# Development: allow common localhost ports (avoid generating tens of thousands of entries)
if not PRODUCTION:
    for port in (3000, 5173, 8000, 8080):
        CSRF_TRUSTED_ORIGINS.append(f"http://localhost:{port}")
        CSRF_TRUSTED_ORIGINS.append(f"http://127.0.0.1:{port}")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
    "courses_and_coach",
    "user_profile",
    "reviews",
    "chat",
    "schedule",
    "booking",
    "payment",
    "admin_panel",
    "authentication",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mami_coach.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mami_coach.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if PRODUCTION:
    # Production: gunakan PostgreSQL dengan kredensial dari environment variables
    # Tambahkan dukungan SSL (Neon membutuhkan SSL). Default sslmode=require.
    # Penting: JANGAN kirimkan 'options' search_path di startup packet (Neon pooler tidak mendukung)
    db_options: dict[str, str] = {}

    # SSL settings (compatible dengan Neon). Dapat dioverride via env.
    sslmode = os.getenv("DB_SSLMODE", "require")  # Neon umumnya membutuhkan 'require'
    if sslmode:
        db_options["sslmode"] = sslmode

    # Opsi tambahan bila dibutuhkan (opsional): path sertifikat
    for env_key, opt_key in [
        ("DB_SSLROOTCERT", "sslrootcert"),
        ("DB_SSLCERT", "sslcert"),
        ("DB_SSLKEY", "sslkey"),
    ]:
        val = os.getenv(env_key)
        if val:
            db_options[opt_key] = val

    # Prefer DATABASE_URL when provided (e.g., from Neon dashboard)
    database_url = os.getenv("DATABASE_URL")
    if database_url and dj_database_url is not None:
        db_cfg = dj_database_url.parse(
            database_url,
            conn_max_age=int(os.getenv("DB_CONN_MAX_AGE", "0")),
            ssl_require=os.getenv("DB_SSL_REQUIRE", "true").lower() == "true",
        )

        # Merge search_path and any explicit SSL overrides into OPTIONS
        merged_options = {**db_cfg.get("OPTIONS", {}), **db_options}
        # Apply explicit SSL files if provided
        for k in ("sslrootcert", "sslcert", "sslkey"):
            if k in db_options:
                merged_options[k] = db_options[k]
        db_cfg["OPTIONS"] = merged_options

        DATABASES = {"default": db_cfg}
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": os.getenv("DB_NAME"),
                "USER": os.getenv("DB_USER"),
                "PASSWORD": os.getenv("DB_PASSWORD"),
                "HOST": os.getenv("DB_HOST"),
                "PORT": os.getenv("DB_PORT"),
                "OPTIONS": db_options,
            }
        }
else:
    # Development: gunakan SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Jakarta"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

if DEBUG:
    STATICFILES_DIRS = [
        BASE_DIR / "static"  # merujuk ke /static root project pada mode development
    ]
else:
    STATIC_ROOT = BASE_DIR / "static"

# Media files (User uploads)
# https://docs.djangoproject.com/en/5.2/howto/manage-files/

# Check if we should use R2 even in development (for testing)
USE_R2 = DEBUG and os.getenv("USE_R2_LOCALLY", "False").lower() == "true" or not DEBUG

if DEBUG and not USE_R2:
    # Development: use local filesystem (default)
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
else:
    # Use Cloudflare R2 (either production or local testing with USE_R2_LOCALLY=True)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": os.getenv("R2_ACCESS_KEY_ID"),
                "secret_key": os.getenv("R2_SECRET_ACCESS_KEY"),
                "bucket_name": os.getenv("R2_BUCKET_NAME"),
                "region_name": "auto",
                "endpoint_url": os.getenv("R2_ENDPOINT_URL"),
                "custom_domain": os.getenv("R2_CUSTOM_DOMAIN"),
                "querystring_auth": False,  # Allow public access to files
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://{os.getenv('R2_CUSTOM_DOMAIN')}/{os.getenv('R2_BUCKET_NAME')}/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Base URL for external callbacks (Midtrans)
BASE_URL = os.getenv('BASE_URL', 'https://kevin-cornellius-mamicoach.pbp.cs.ui.ac.id')

# Set PostgreSQL search_path after each new connection (avoid startup 'options' not supported by Neon pooler)
if PRODUCTION:
    from django.db.backends.signals import connection_created  # type: ignore
    from django.dispatch import receiver  # type: ignore

    @receiver(connection_created)
    def set_postgres_search_path(sender, connection, **kwargs):  # pragma: no cover
        try:
            if connection.vendor == "postgresql" and SCHEMA:
                with connection.cursor() as cursor:
                    cursor.execute(f"SET search_path TO {SCHEMA}")
        except Exception:
            # Don't crash the app if setting search_path fails; log if needed
            pass
